### ISSUE TITLE
Support for multiple Series

### ISSUE THREAD

**Issue by dankles** [anansi-project/rfcs#23]
Would it be possible to support a given Title be part of multiple Series? It would be useful for crossovers. 

In an example of [Witchblade / The Darkness](https://comicvine.gamespot.com/witchblade-the-darkness-1-witchbladethe-darkness-p/4000-124841/), the title would be part of both the Witchblade and The Darkness series. I understand most would simply file it under a single series called "Witchblade / The Darkness", but I think some would appreciate the option to individually catalog them.

**Comment by gotson** [comment]
I lack context about US comics, can you clarify a bit how this series is actually 2? The link you provide is a single series apparently.

I had a note / question about whether a book could be part of multiple series, but no one confirmed this so far.

**Comment by dankles** [comment]
This isn't a US comic thing as far as I'm aware, just a personal preference. The example is a crossover of [Witchblade](https://comicvine.gamespot.com/witchblade/4050-7300/) and [The Darkness](https://comicvine.gamespot.com/the-darkness/4050-5868/). It's also [part of a story arc](https://comicvine.gamespot.com/witchblade-darkness/4045-55773/) between those two universes. 

Looking at that story arc I linked, there would be 4 titles with 4 unique series within that story arc if going by traditional means:

|Title | Series |
|:----|:-------|
| Witchblade | Witchblade |
| Witchblade / The Darkness | Witchblade / The Darkness |
| The Darkness / Witchblade | The Darkness / Witchblade |
| The Darkness | The Darkness |

But if we could split the series on those crossover stories, it would only be 2 unique series:

|Title | Series 1 | Series 2 |
|:----|:----------|:---------|
| Witchblade | Witchblade | |
| Witchblade / The Darkness | The Darkness | Witchblade |
| The Darkness / Witchblade | The Darkness | Witchblade |
| The Darkness | The Darkness | |

**Comment by reverendj1** [comment]
Supporting multiple series and issues would also be useful in the case of omnibuses/trade paperbacks. I think you are right in that these should be handled both in terms of the book itself as a series, and the issues that make up the collection. Take for instance, The Deadpool: Adamantium Collection, https://comicvine.gamespot.com/deadpool-the-adamantium-collection/4050-99248/. As you can see, it comprises different issues of several different series. This collection isn't a single cross-over/story arc, but several that someone getting into Deadpool may enjoy.

For why this is important, say I'm reading the Cable & Deadpool (one of the series with issues in this collection) and I finish reading issue 19. I would need some way of knowing that the next several issues are in this book. If I am reading Deadpool v2 and finish issue 15, I would also need to know that the next several issues are in this book.

**Comment by gotson** [comment]
I have updated the data model, a Book can have 0 to N series now.
